#include "SrcWrapper.h"
#include "src/gpio.c"
#include "src/i2c.c"
#include "src/interrupt_controller.c"
#include "src/sio.c"
#include "src/spi.c"
#include "src/syscall.c"
#include "src/riscv/mtime.c"